version: "3.8"

services:
  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./lib:/app/lib
      - ./build-run.sh:/app/build-run.sh
    working_dir: /app

  db:
    image: mysql:8.0
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
