services:
  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./lib:/app/lib
      - ./build-run.sh:/app/build-run.sh
    working_dir: /app
    stdin_open: true
    tty: true

  db:
    image: mysql:8.0
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - ./docs/db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
