CREATE TABLE Wallet (
    id CHAR(36) PRIMARY KEY,
    address VARCHAR(255) NOT NULL,
    balance DOUBLE NOT NULL DEFAULT 0
);

CREATE TABLE BitcoinWallet (
   wallet_id CHAR(36) PRIMARY KEY,
   SATOSHI_PER_BYTE DOUBLE NOT NULL,
   CONSTRAINT fk_bitcoin_wallet FOREIGN KEY (wallet_id) REFERENCES Wallet(id) ON DELETE CASCADE
);

CREATE TABLE EthereumWallet (
    wallet_id CHAR(36) PRIMARY KEY,
    GAS_PRICE DOUBLE NOT NULL,
    GAS_LIMIT INT NOT NULL,
    CONSTRAINT fk_ethereum_wallet FOREIGN KEY (wallet_id) REFERENCES Wallet(id) ON DELETE CASCADE
);

CREATE TABLE Transaction (
    id CHAR(36) PRIMARY KEY,
    wallet_id CHAR(36) NOT NULL,
    sourceAddress VARCHAR(255) NOT NULL,
    destinationAddress VARCHAR(255) NOT NULL,
    amount DOUBLE NOT NULL,
    fee DOUBLE NOT NULL,
    createdAt DATETIME NOT NULL,
    sizeInBytes INT NOT NULL,
    priority ENUM('ECONOMIQUE', 'STANDARD', 'RAPIDE') NOT NULL DEFAULT 'STANDARD',
    status ENUM('PENDING', 'CONFIRMED', 'REJECTED') NOT NULL DEFAULT 'PENDING',
    CONSTRAINT fk_transaction_wallet FOREIGN KEY (wallet_id) REFERENCES Wallet(id) ON DELETE CASCADE
);
